#ifndef _MCP2515_REGS__H_
#define _MCP2515_REGS__H_

/* RXBxSIDH */
#define RXB0SIDH_REG				(0x61)
#define RXB1SIDH_REG				(0x71)

/* RXBxSIDL */
#define RXB0SIDL_REG				(0x62)
#define RXB1SIDL_REG				(0x72)
#define RXBxSIDL_SID_OFF			(0x5)
#define RXBxSIDL_SID_MASK			(0x7 << RXBxSIDL_SID_OFF)
#define RXBxSIDL_SRR_OFF			(0x4)
#define RXBxSIDL_SRR_MASK			(1 << RXBxSIDL_SRR_OFF)
#define RXBxSIDL_IDE_OFF			(0x3)
#define RXBxSIDL_IDE_MASK			(1 << RXBxSIDL_IDE_OFF)
#define RXBxSIDL_EID_OFF			(0x0)
#define RXBXSIDL_EID_MASK			(0x3 << RXBxSIDL_EID_OFF)

/* RXBxDLC */
#define RXB0DLC_REG					(0x65)
#define RXB1DLC_REG					(0x75)
#define RXBxDLC_DLC_OFF				(0x00)
#define RXBxDLC_DLC_MASK			(0x0F << RXBxDLC_DLC_OFF)
#define RXBxDLC_RTR_OFF				(0x06)
#define RXBxDLC_RTR_MASK			(0x01 << RXBxDLC_RTR_OFF)

/* BFPCTRL */
#define BFPCTRL_REG					(0x0C)
#define BFPCTRL_B0BFM_OFF			(0x00)
#define BFPCTRL_B0BFM_MASK			(0x01 << BFPCTRL_B0BFM_OFF)
#define BFPCTRL_B1BFM_OFF			(0x01)
#define BFPCTRL_B1BFM_MASK			(0x01 << BFPCTRL_B1BFM_OFF)
#define BFPCTRL_B0BFE_OFF			(0x02)
#define BFPCTRL_B0BFE_MASK			(0x01 << BFPCTRL_B0BFE_OFF)
#define BFPCTRL_B1BFE_OFF			(0x03)
#define BFPCTRL_B1BFE_MASK			(0x01 << BFPCTRL_B1BFE_OFF)
#define BFPCTRL_B0BFS_OFF			(0x04)
#define BFPCTRL_B0BFS_MASK			(0x01 << BFPCTRL_B0BFS_OFF)
#define BFPCTRL_B1BFS_OFF			(0x05)
#define BFPCTRL_B1BFS_MASK			(0x01 << BFPCTRL_B1BFS_OFF)

/* TXRTSCTRL */
#define TXRTSCTRL_REG				(0x0D)
#define TXRTSCTRL_B0RTSM_OFF		(0x00)
#define TXRTSCTRL_B0RTSM_MASK		(0x01 << TXRTSCTRL_B0RTSM_OFF)
#define TXRTSCTRL_B1RTSM_OFF		(0x01)
#define TXRTSCTRL_B1RTSM_MASK		(0x01 << TXRTSCTRL_B1RTSM_OFF)
#define TXRTSCTRL_B2RTSM_OFF		(0x02)
#define TXRTSCTRL_B2RTSM_MASK		(0x01 << TXRTSCTRL_B2RTSM_OFF)
#define TXRTSCTRL_B0RTS_OFF			(0x03)
#define TXRTSCTRL_B0RTS_MASK		(0x01 << TXRTSCTRL_B0RTS_OFF)
#define TXRTSCTRL_B1RTS_OFF			(0x04)
#define TXRTSCTRL_B1RTS_MASK		(0x01 << TXRTSCTRL_B1RTS_OFF)
#define TXRTSCTRL_B2RTS_OFF			(0x05)
#define TXRTSCTRL_B2RTS_MASK		(0x01 << TXRTSCTRL_B2RTS_OFF)


/* CANSTAT */
#define CANSTAT_REG					(0x0E)
#define CANSTAT_ICOD_OFF			(0x01)
#define CANSTAT_ICOD_MASK			(0x07 << CANSTAT_ICOD_OFF)
#define CANSTAT_OPMOD_OFF			(0x05)
#define CANSTAT_OPMOD_MASK			(0x07 << CANSTAT_OPMOD_OFF)

/* CANCTRL */
#define CANCTRL_REG					(0x0F)
#define CANCTRL_CLKPRE_OFF			(0x00)
#define CANCTRL_CLKPRE_MASK			(0x03 << CANCTRL_CLKPRE_OFF)
#define CANCTRL_CLKEN_OFF			(0x02)
#define CANCTRL_CLKEN_MASK			(0x01 << CANCTRL_CLKPRE_OFF)
#define CANCTRL_OSM_OFF				(0x03)
#define CANCTRL_OSM_MASK			(0x01 << CANCTRL_OSM_OFF)
#define CANCTRL_ABAT_OFF			(0x04)
#define CANCTRL_ABAT_MASK			(0x01 << CANCTRL_ABAT_OFF)
#define CANCTRL_REQOP0_OFF			(0x05)
#define CANCTRL_REQOP0_MASK			(0x07 << CANCTRL_REQOP0_OFF)

/* CNF1 */
#define CNF1_REG					(0x2A)
#define CNF1_BRP_OFF				(0x0)
#define CNF1_BRP_MASK				(0x3F << CNF1_BRP_OFF)
#define CNF1_SJW_OFF				(0x06)
#define CNF1_SJW_MASK				(0x3 << CNF1_SJW_OFF)

/* CANINTE */
#define CANINTE_REG					(0x2B)
#define CANINTE_RX0IE_OFF			(0x00)
#define CANINTE_RX0IE_MASK			(0x01 << CANINTE_RX0IE_OFF)
#define CANINTE_RX1IE_OFF			(0x01)
#define CANINTE_RX1IE_MASK			(0x01 << CANINTE_RX1IE_OFF)
#define CANINTE_TX0IE_OFF			(0x02)
#define CANINTE_TX0IE_MASK			(0x01 << CANINTE_TX0IE_OFF)
#define CANINTE_TX1IE_OFF			(0x03)
#define CANINTE_TX1IE_MASK			(0x01 << CANINTE_TX1IE_OFF)
#define CANINTE_TX2IE_OFF			(0x04)
#define CANINTE_TX2IE_MASK			(0x01 << CANINTE_TX2IE_OFF)
#define CANINTE_ERRIE_OFF			(0x05)
#define CANINTE_ERRIE_MASK			(0x01 << CANINTE_ERRIE_OFF)
#define CANINTE_WAKIE_OFF			(0x06)
#define CANINTE_WAKIE_MASK			(0x01 << CANINTE_WAKIE_OFF)
#define CANINTE_MERRE_OFF			(0x07)
#define CANINTE_MERRE_MASK			(0x01 << CANINTE_MERRE_OFF)

/* CANINTF */
#define CANINTF_REG					(0x2C)
#define CANINTF_MERRF   			BIT(7)
#define CANINTF_WAKIF				BIT(6)
#define CANINTF_ERRIF				BIT(5)
#define CANINTF_TX2IF				BIT(4)
#define CANINTF_TX1IF				BIT(3)
#define CANINTF_TX0IF				BIT(2)
#define CANINTF_RX1IF				BIT(1)
#define CANINTF_RX0IF				BIT(0)

/* EFLG */
#define EFLG_REG					(0x2D)

/* CNF2 */
#define CNF2_REG					(0x29)
#define CNF2_PRSEG_OFF				(0x00)
#define CNF2_PRSEG_MASK				(0x07 << CNF2_PRSEG_OFF)
#define CNF2_PHSEG_OFF				(0x03)
#define CNF2_PHSEG_MASK				(0x07 << CNF2_PHSEG_OFF)
#define CNF2_SAM_OFF				(0x06)
#define CNF2_SAM_MASK				(0x01 << CNF2_SAM_OFF)
#define CNF2_BTLMODE_OFF			(0x07)
#define CNF2_BTLMODE_MASK			(0x01 << CNF2_BTLMODE_OFF)

/* CNF3 */
#define CNF3_REG					(0x28)
#define CNF3_PHSEG2_OFF				(0x00)
#define CNF3_PHSEG2_MASK			(0x07 << CNF3_PHSEG2_OFF)
#define CNF3_WAKFIL_OFF				(0x06)
#define CNF3_WAKFIL_MASK			(0x01 << CNF3_WAKFIL_OFF)
#define CNF3_SOF_OFF				(0x07)
#define CNF3_SOF_MASK				(0x01 << CNF3_SOF_OFF)

/* TXBxCTRL */
#define TXB0CTRL_REG				(0x30)
#define TXB1CTRL_REG				(0x40)
#define TXB2CTRL_REG				(0x50)
#define TXBxCTRL_TXP_OFF			(0x00)
#define TXBxCTRL_TXP_MASK			(0x03 << TXBxCTRL_TXP_OFF)
#define TXBxCTRL_TXREQ_OFF			(0x03)
#define TXBxCTRL_TXREQ_MASK			(0x01 << TXBxCTRL_TXREQ_OFF)
#define TXBxCTRL_TXERR_OFF			(0x04)
#define TXBxCTRL_TXERR_MASK			(0x01 << TXBxCTRL_TXERR_OFF)
#define TXBxCTRL_MLOA_OFF			(0x05)
#define TXBxCTRL_MLOA_MASK			(0x01 << TXBxCTRL_MLOA_OFF)
#define TXBxCTRL_ABTF_OFF			(0x06)
#define TXBxCTRL_ABTF_MASK			(0x01 << TXBxCTRL_ABTF_OFF)


/* RXB0CTRL */
#define RXB0CTRL_REG				(0x60)
#define RXB0CTRL_FILHIT0_OFF		(0x00)
#define RXB0CTRL_FILHIT0_MASK		(0x01 << RXB0CTRL_FILHIT0_OFF)
#define RXB0CTRL_BUKT1_OFF			(0x01)
#define RXB0CTRL_BUKT1_MASK			(0x01 << RXB0CTRL_BUKT1_OFF)
#define RXB0CTRL_BUKT_OFF 			(0x02)
#define RXB0CTRL_BUKT_MASK 			(0x01 << RXB0CTRL_BUKT_OFF)
#define RXB0CTRL_RXRTR_OFF			(0x03)
#define RXB0CTRL_RXRTR_MASK			(0x01 << RXB0CTRL_RXRTR_OFF)
#define RXB0CTRL_RXM_OFF			(0x05)
#define RXB0CTRL_RXM_MASK			(0x03 << RXB0CTRL_RXM_OFF)
#define RXB0CTRL_RXM_FLT_OFF		(0x03 << RXB0CTRL_RXM_OFF)

/* RXB1CTRL */
#define RXB1CTRL_REG				(0x70)
#define RXB1CTRL_FILHIT_OFF			(0x00)
#define RXB1CTRL_FILHIT_MASK		(0x7 << RXB1CTRL_FILHIT_OFF)
#define RXB1CTRL_RXRTR_OFF			(0x03)
#define RXB1CTRL_RXRTR_MASK			(0x01 << RXB1CTRL_RXRTR_OFF)
#define RXB1CTRL_RXM_OFF			(0x05)
#define RXB1CTRL_RXM_MASK			(0x03 << RXB1CTRL_RXM_OFF)
#define RXB1CTRL_RXM_FLT_OFF		(0x03 << RXB1CTRL_RXM_OFF)

/* RXB0 and RXB1 */
#define MCP2515_RXB0_START_ADDRESS	(0x66)
#define MCP2515_RXB1_START_ADDRESS	(0x76)


#endif // _MCP2515_REGS__H_